---
# Проверка пользователей на всех хостах
- name: Verify users
  hosts: all
  tasks:
    # Проверка наличия пользователя "ansible"
    - name: Ensure test_user exists
      ansible.builtin.command:
        cmd: "id ansible"
      register: result
      failed_when: result.rc != 0
      changed_when: false
